services:
  - type: web
    name: django-app
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn ilkproje.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ilkproje.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        value: postgresql://rootuser:JHrRWGxq2ub4NfX64M15MWemWzNahkDt@dpg-d0jmo3nfte5s7380l03g-a.frankfurt-postgres.render.com/djangodatabase_akns