# Generated by Django 5.1.7 on 2025-03-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yazi',
            old_name='olusturma_tarihi',
            new_name='olusturulma_tarihi',
        ),
        migrations.AddField(
            model_name='yazi',
            name='goruntulenme_sayisi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='yazi',
            name='yazar',
            field=models.CharField(default='Bilinmiyor', max_length=100),
        ),
    ]
